### PR TITLE
Temporary PR for Build 2 verify.

### PR DESCRIPTION
**Pull request by MingkaiChen**
Temporary PR for Build 2 verify.

### CODE REVIEW

**Comment by MingkaiChen** [comment]
Note that the following routes exits for now:

/map/[1-3]
/login
/signup
/forgot

**Review by NotakingButaGod — APPROVED** [review]
Pass

**Comment by Zhangwen-Hu** [comment]
LGTM

**Review by Zhangwen-Hu — APPROVED** [review]
LGTM

**Pull request merged**
